package org.snapscript.develop.http.display;

public enum DisplayKey {
   IMAGE_FOLDER,
   PROJECT_FONT_COLOR,
   PROJECT_BACKGROUND_COLOR,
   PROJECT_MENU_COLOR,
   FANCY_TREE_CSS_FILE,
   W2UI_CSS_FILE,
   CONSOLE_BACKGROUND_COLOR,
   DIALOG_BACKGROUND_COLOR,
   DIALOG_FONT_COLOR,
   DIALOG_PANEL_COLOR,
   DIALOG_ENTRY_HIGHLIGHT_COLOR,
   DIALOG_ENTRY_BORDER_COLOR,
   TREE_BACKGROUND_COLOR;
}
